#!/bin/sh
#
# xmtp2km_rm: xmtp2km uninstaller
#
# Derivation: Copyright (C) 2005 Xygnada Technology, Inc.
# Copyright (C) 2001 Alessandro Rubini and Jonathan Corbet
# Copyright (C) 2001 O'Reilly & Associates
#
# The source code in this file can be freely used, adapted,
# and redistributed in source or binary form, so long as an
# acknowledgment appears in derived source files.  The citation
# should list that the code comes from the book "Linux Device
# Drivers" by Alessandro Rubini and Jonathan Corbet, published
# by O'Reilly & Associates.   No warranty is attached;
# we cannot take responsibility for errors or fitness for use.
#

module="xmtp2km"
device="xmtp2km"

# invoke rmmod with all arguments we got
/sbin/rmmod $module $* || exit 1

# Remove stale nodes

rm -f /dev/${device} /dev/${device}[0-3] 
