#!/bin/sh
#Make sure that udev/devfs zaptel device
#has come up.
cnt=0
max_delay=30
i=0

echo -n "Waiting for zaptel device /dev/zap ..."
#for ((i=0;i<$max_delay;i++))
while [ $i != $max_delay ]
do
	if [ -e /dev/zap ]; then
        	break;
	fi
	echo -n "." 
	i=$((i+1));
  	sleep 2
done
echo " " 
if [ ! -e /dev/zap ]; then
	echo
	echo "Error: Zaptel device failed to come up";
        echo "Possible Cause: UDEV not installed!";
	echo
	exit 1
fi 

sleep 1

ztcfg -v

